/* members.js: coordinators add, edit and remove members */
const loadTeam=async()=>{S.team=await api('/members/admin')};
function teamV(){return `<h2>Add a member</h2><div class="card"><label for="an">Name</label><input id="an"><label for="ae">Email</label><input id="ae" type="email"><label for="ar">Role</label><input id="ar" placeholder="e.g. Brakes member"><label>Subsystems</label><div class="row" id="asub">${SUBS.map(s=>`<label class="row" style="margin:0;gap:4px"><input type="checkbox" value="${s[0]}"> ${s[1]}</label>`).join('')}</div><p><button class="pri" id="aa">Add member</button></p></div>
<h2>Team (${S.team.filter(m=>m.is_active).length})</h2><div class="grid">${S.team.map(m=>`<div class="card row" style="flex-wrap:nowrap;opacity:${m.is_active?1:.5}">${av(m)}<div style="flex:1;min-width:0"><b>${esc(m.name)}</b> ${m.is_coordinator?'<span class="pill" style="--c:var(--b)">Admin</span>':''}${m.is_active?'':'<span class="pill" style="--c:var(--r)">Removed</span>'}<div class="mu">${esc(m.role_text)}</div><div class="mu" style="overflow-wrap:anywhere">${esc(m.email)}</div></div><div><button data-em="${m.id}">Email</button> ${m.is_coordinator||!m.is_active?'':`<button class="dng" data-rm="${m.id}">Remove</button>`}</div></div>`).join('')}</div>`}
function teamB(){const refresh=async()=>{await Promise.all([loadTeam(),loadWho()]);view(true)};
 $('#aa').onclick=()=>run(async()=>{const name=$('#an').value.trim(),subs=[...document.querySelectorAll('#asub input:checked')].map(i=>i.value);
  const r=await api('/members',{method:'POST',body:{name,email:$('#ae').value.trim(),role_text:$('#ar').value.trim()||'Member',subsystems:subs}});
  modal(`<div class="row"><h3 style="flex:1">Member added</h3><button class="cls">Close</button></div><p>Temporary password for <b>${esc(r.member.name)}</b>:</p><p class="of" style="font-size:1.2rem;color:var(--g)">${esc(r.temporary_password)}</p><p class="mu">It was also emailed. They must change it at first login.</p>`);await refresh()});
 document.querySelectorAll('[data-em]').forEach(b=>b.onclick=()=>run(async()=>{const m=S.team.find(x=>x.id===+b.dataset.em),e=prompt('Email for '+m.name,m.email);if(!e||e===m.email)return;await api('/members/'+m.id,{method:'PATCH',body:{email:e.trim()}});toast('Email updated');await refresh()}));
 document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>run(async()=>{const m=S.team.find(x=>x.id===+b.dataset.rm);if(!confirm('Remove '+m.name+'? They will no longer be able to log in.'))return;await api('/members/'+m.id,{method:'DELETE'});toast('Removed '+m.name);await refresh()}))}
VIEWS.team={html:teamV,bind:teamB,load:loadTeam};
