/* workshop.js: Who's In, dashboard and workshop timing */
const loadWho=async()=>{S.who=await api('/attendance/today/whos-in')};
const loadW=async()=>{S.w=await api('/workshop');syncClock(S.w)};
let flt='all',qry='';
const stats=c=>Object.keys(c).map(k=>`<div class="card stat" style="--c:${colors[k]}"><b>${c[k]}</b>${label[k]}</div>`).join('');
function pitGrid(){const l=roster().filter(m=>(flt==='all'||m.status===flt)&&(m.name+' '+m.role_text).toLowerCase().includes(qry.toLowerCase()));
 return l.map(m=>`<div class="card row" data-mid="${m.id}" tabindex="0" role="button" style="flex-wrap:nowrap">${av(m,m.status)}<div style="flex:1;min-width:0"><b>${esc(m.name)}</b> ${m.is_coordinator?'<span class="pill" style="--c:var(--b)">Admin</span>':''}<div class="mu">${esc(m.role_text)}</div><span class="pill" style="--c:${colors[m.status]}">${label[m.status]}${m.eta&&m.status==='coming'?' · ETA '+m.eta:''}</span> <span class="mu">${m.time_in?'In '+m.time_in:''}${m.time_out?' · Out '+m.time_out:''}</span></div></div>`).join('')||'<p class="mu">No one matches. Try another filter.</p>'}
function pitV(){return `<div class="card" id="cd" style="margin-top:10px">${cdText()}</div><h2>Today · ${S.w.start} to ${S.w.end}</h2><div class="row">${stats(S.who.counts)}</div><h2>Who's in</h2><input id="sq" type="search" placeholder="Search name or role" value="${esc(qry)}"><div class="row" style="margin:8px 0">${['all','present','coming','absent','not_updated'].map(k=>`<button data-f="${k}" class="${flt===k?'on':''}">${k==='all'?'All':label[k]}</button>`).join('')}</div><div class="grid" id="pg">${pitGrid()}</div>`}
function openM(id){const m=rowOf(id);if(!m)return;const showT=S.me.is_coordinator||id===S.me.id,ts=S.tasks.filter(t=>t.assigned_to===id&&t.status!=='done');
 modal(`<div class="row">${av(m,m.status)}<div style="flex:1"><h3>${esc(m.name)}</h3><div class="mu">${esc(m.role_text)}</div></div><button class="cls">Close</button></div><p><span class="pill" style="--c:${colors[m.status]}">${label[m.status]}${m.eta&&m.status==='coming'?' · ETA '+m.eta:''}</span> <span class="mu">${m.time_in?'In '+m.time_in:''}${m.time_out?' · Out '+m.time_out:''}</span></p><p class="mu">Branch: ${esc(m.branch||'-')} · Year: ${esc(m.year||'-')} · Blood: ${esc(m.blood_group||'-')}</p>${m.phone?`<a href="tel:${esc(m.phone)}"><button class="pri">Call ${esc(m.phone)}</button></a>`:'<p class="mu">No phone added yet.</p>'}${showT?`<h2>Open tasks</h2>${ts.map(t=>`<div style="margin:6px 0">${esc(t.title)}${bar(t.progress)}</div>`).join('')||'<p class="mu">None.</p>'}`:''}`)}
function pitB(){document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{flt=b.dataset.f;view(true)});
 const bindCards=()=>document.querySelectorAll('[data-mid]').forEach(c=>{c.onclick=()=>openM(+c.dataset.mid);c.onkeydown=e=>{if(e.key==='Enter')openM(+c.dataset.mid)}});
 $('#sq').oninput=e=>{qry=e.target.value;$('#pg').innerHTML=pitGrid();bindCards()};bindCards()}
function dashV(){const open=S.tasks.filter(t=>t.status!=='done').length;return `<h2>Dashboard</h2><div class="row">${stats(S.who.counts)}<div class="card stat" style="--c:var(--b)"><b>${open}</b>Open tasks</div></div><h2>Needs a nudge</h2><div class="grid">${roster().filter(m=>m.status==='not_updated').map(m=>`<div class="card row">${av(m)}<span>${esc(m.name)}</span></div>`).join('')||'<p class="mu">Everyone has updated.</p>'}</div>`}
function timeV(){return `<h2>Workshop timing</h2><div class="card"><label for="ts">Start</label><input type="time" id="ts" value="${S.w.start}"><label for="te">End</label><input type="time" id="te" value="${S.w.end}"><p><button class="pri" id="tn">Update and notify all</button></p></div>`}
function timeB(){$('#tn').onclick=()=>run(async()=>{const r=await api('/workshop',{method:'PUT',body:{start:$('#ts').value,end:$('#te').value}});toast(r.changed?'Timing updated. Everyone was emailed.':'No change');await loadW();view(true)})}
VIEWS.pit={html:pitV,bind:pitB,load:async()=>{await Promise.all([loadWho(),loadTasks(),loadW()])}};
VIEWS.dash={html:dashV,load:async()=>{await Promise.all([loadWho(),loadTasks()])}};
VIEWS.time={html:timeV,bind:timeB,load:loadW};
